FROM python:3.10.4
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
#requiremenets.txt == selenium

RUN pip3 install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./app /code/app